# -*- coding: utf-8 -*-
"""ML-Pratical-4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EiHh-B25IWnV7a0_NyLHSFhCTKDYKpo1
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

x = pd.read_csv("cancer.csv")
a = np.array(x)
y = a[:,30]

x = np.column_stack((x.State))

x.shape

print (x),(y)